version: "3.9"
services:
  ### NGINX #########################################
  nginx:
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
  ### NODE #########################################
  node-app:
#    deploy:
#      replicas: 2 # we can increase it in future to as many as we want
#      restart_policy:
#        condition: any
#      update_config:
#        parallelism: 2
#        delay: 15s
    build:
      context: ./server
      dockerfile: Dockerfile.Prod
      args:
        - NODE_ENV=production
        - PORT=${PORT}
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
    env_file:
      - ./.env
