version: "3.9"
services:
  nginx:
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
  node-screenshot:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    command: node server.js
